# Generated by Django 4.1.1 on 2022-10-11 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_question_sondage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('parent', models.ManyToManyField(blank=True, related_name='parent_tag', to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Lieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('parent', models.ManyToManyField(blank=True, related_name='parent_location', to='api.lieux')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('parent', models.ManyToManyField(blank=True, related_name='parent_categorie', to='api.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=155, null=True)),
                ('lastname', models.CharField(blank=True, max_length=155, null=True)),
                ('temp_name', models.CharField(blank=True, max_length=155, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=155, null=True)),
                ('profile_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.photo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('prix', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=300)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('categorie', models.ManyToManyField(blank=True, related_name='categorie', to='api.categorie')),
                ('lieux', models.ManyToManyField(blank=True, related_name='lieux', to='api.lieux')),
                ('photo', models.ManyToManyField(blank=True, related_name='photo', to='api.photo')),
                ('tag', models.ManyToManyField(blank=True, related_name='tag', to='api.tag')),
            ],
        ),
    ]
