# Generated by Django 4.1.1 on 2022-10-11 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_annonce_created_at_annonce_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.author'),
        ),
    ]
