# Generated by Django 4.1.1 on 2022-10-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_photo_alter_tag_parent_lieux_categorie_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='lieux',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.DeleteModel(
            name='Annonce',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Lieux',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
